layout_spectrum: 0.6485329454299062
typography_spectrum: 0.5385254963766783
color:
  brandStrength: 0.4369358962867409
  lightness: 0.9813161718193442
  saturation: 0.10314829624257982
  rhythmicContrast: 0.7787940700072795
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: Nature Shapes
title: Nature Shapes
description: >-
  "Without the interfering hands of civilization, Nature will always shape
  itself to its own needs"
